# Generated by Django 5.2.7 on 2025-10-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll_no', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('marks', models.IntegerField(max_length=10)),
            ],
        ),
    ]
